### ISSUE TITLE
Setup container registry

### ISSUE THREAD

**Issue by KubaPawlak** [MagdalenaPakula/StudentReportLLM#8]
# Overview
Configure the CI/CD pipeline to automatically push the built container images to some repository.

# Questions
1. Should the repository be local or remote?

# Notes
1. In order for the image to be pushed, all the automatic tests **must** pass

**Comment by MagdalenaPakula** [comment]
Done in the pipeline

**Comment by MagdalenaPakula** [comment]
at least thats how i understood the cicd pipeline...
